services:
  grafana:
    image: grafana/grafana:main
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      # Pass env vars to container
      - POSTGRES_DBNM=${POSTGRES_DBNM}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASS=${POSTGRES_PASS}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - postgres_network
    # Add this entrypoint to substitute variables

  postgres:
    image: postgres:17-alpine
    container_name: postgresql_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DBNM}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  grafana-data:
    driver: local
  postgres_data:
    driver: local

networks:
  postgres_network:
    driver: bridge
