{
 "title": "Cat'n Dogs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Feedback Rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "catndogdb",
     "rawSql": "SELECT\n    100*SUM((grade <> 0)::int)::float/COUNT(grade)\nFROM feedback"
    }
   ]
  },
  {
   "title": "Satisfaction rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "catndogdb",
     "rawSql": "SELECT \n    100*SUM((grade = 1)::int)::float / \n    (SUM((grade = 1)::int) + SUM((grade = -1)::int))\nFROM feedback"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "catndogdb",
     "rawSql": "SELECT 100*sum((success=True)::int)::float / count(success) \nFROM predictionlog"
    }
   ]
  },
  {
   "title": "Total Queries ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "catndogdb",
     "rawSql": "SELECT COUNT(grade) FROM feedback"
    }
   ]
  },
  {
   "title": "Response Time (ms)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dataset": "catndogdb",
     "rawSql": "SELECT \"timestamp\", inference_time_ms FROM predictionlog LIMIT 50 "
    }
   ]
  }
 ]
}