apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgresql_db:5432
    database: ${POSTGRES_DBNM}
    user: ${POSTGRES_USER}
    secureJsonData:
      password: ${POSTGRES_PASS}
    jsonData:
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
    isDefault: true
    editable: true