name: CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        pip install -r requirements/base.txt
        pip install pytest
    
    - name: Setup test environment
      run: |
        mkdir -p data/processed/models
        touch data/processed/models/cats_dogs_model.keras
    - name : Create Fake .env
      run : |
        cat > .env << EOF
          POSTGRES_DBNM=catndogdb
          POSTGRES_USER=myusername
          POSTGRES_PASS=mycomplicatedpassword
          POSTGRES_PORT=5433
        EOF
    - name : Setup PostgreSQL
      run : |
        make up
    
    - name: Start API and test
      run: |
        python scripts/run_api.py &
        sleep 25
        #python tests/test_api_simple.py
        pytest
    - name : Stop PostgreSQL
      run : |
        make down